export const demoMembers = [
  {
    id: "demo-1",
    fullName: "Ava Lin",
    email: "ava@oao.club",
    phone: "+86 138-0000-1001",
    studentId: "20261001",
    className: "G11-3",
    emergencyContact: "Parent / +86 138-0000-9001",
    notes: "Enjoys event coverage and fast turnarounds.",
    skills: ["Photography", "Editing", "Color Grading"],
    availability: ["Mon PM", "Wed PM", "Sat"],
    projectPreferences: ["Sports", "Portrait", "Event Docs"],
    profileStatus: "active",
    role: "MEMBER",
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-2",
    fullName: "Noah Chen",
    email: "noah@oao.club",
    phone: "+86 138-0000-1002",
    studentId: "20261002",
    className: "G10-2",
    emergencyContact: "Guardian / +86 138-0000-9002",
    notes: "Strong on logistics and stage coverage.",
    skills: ["Videography", "Audio", "Scheduling"],
    availability: ["Tue PM", "Thu PM", "Sun"],
    projectPreferences: ["Stage", "Interviews", "Behind the Scenes"],
    profileStatus: "active",
    role: "ADMIN",
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-3",
    fullName: "Mia Zhou",
    email: "mia@oao.club",
    phone: "+86 138-0000-1003",
    studentId: "20261003",
    className: "G12-1",
    emergencyContact: "Parent / +86 138-0000-9003",
    notes: "Wants to work on campaign visuals.",
    skills: ["Design", "Copywriting", "Photography"],
    availability: ["Mon PM", "Fri PM", "Sat"],
    projectPreferences: ["Recruitment", "Brand Content", "Campus Life"],
    profileStatus: "active",
    role: "MEMBER",
    createdAt: new Date().toISOString(),
  },
];

export const demoTimetable = [
  {
    id: "tt-1",
    title: "Weekly Editorial Standup",
    description: "Review upcoming events and assign capture leads.",
    location: "Media Lab",
    startAt: new Date(Date.now() + 86400000).toISOString(),
    endAt: new Date(Date.now() + 90000000).toISOString(),
    notifyMembers: true,
    status: "PUBLISHED",
    position: 0,
  },
  {
    id: "tt-2",
    title: "Sports Day Coverage",
    description: "Photo and video coverage for athletics finals.",
    location: "Main Stadium",
    startAt: new Date(Date.now() + 172800000).toISOString(),
    endAt: new Date(Date.now() + 176400000).toISOString(),
    notifyMembers: true,
    status: "DRAFT",
    position: 1,
  },
];

export const demoMissions = [
  {
    id: "ms-1",
    title: "Publish Volleyball Photo Recap",
    description: "Curate 18 finals shots and prepare caption copy for release.",
    ownerName: "Ava Lin",
    priority: "high",
    status: "IN_PROGRESS",
    dueDate: new Date(Date.now() + 48 * 3600000).toISOString(),
  },
  {
    id: "ms-2",
    title: "Recruitment Booth Promo Reel",
    description: "Assemble 30-second teaser video for recruitment week.",
    ownerName: "Noah Chen",
    priority: "medium",
    status: "TODO",
    dueDate: new Date(Date.now() + 72 * 3600000).toISOString(),
  },
];
